#!/usr/bin/python -u
#
# CS3700, Spring 2015
# Project 2 Starter Code


# sending command script
# ./3700send <recv_host>:<recv_port>

# receiver command script
# ./3700recv <recv_port>


# code only work if network is perfectly reliable, modify it to handle:
# delayed packet: actually delay the number of packet that should be delayed in the sender
# packet retransmission --> dropped packet: wait for ROT and send back 3 ACK of previous received packet 
# duplicate packet: 
# reordered handling:  

# bandwidth
# latency


# drop
# delay
# reorder
# duplicate


import sys
import socket
import time
import datetime
import select
import json

MSG_SIZE = 1500
DATA_SIZE = 1000
TIMEOUT = 30
SEQUENCE = 0
PACKETS_MEMORY = []

# Bind to localhost and an ephemeral port
IP_PORT = sys.argv[1]
UDP_IP = IP_PORT[0:IP_PORT.find(":")]
UDP_PORT = int(IP_PORT[IP_PORT.find(":")+1:])
dest = (UDP_IP, UDP_PORT)

# UDP_PORT = int(sys.argv[1]) # Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
sock.settimeout(TIMEOUT)

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

# change maximum data size
# implementation for sliding window
# getting RTT for delay (dropped packet (duplicated acks) as well as delayed packet as well) --> 
# way to retransmitted and 
# reordered packet: receiver reorder base on sequence number
def send_next_packet():
  global SEQUENCE
  data = sys.stdin.read()
  dataSize = len(data)
#  print("data is: ")
#  print(data)
#  print("dataSize is: ")
#  print(dataSize)
  if dataSize <= DATA_SIZE:
#    print("dataSize is smaller than DATA_SIZE")
    if (dataSize > 0):
#      print("dataSize is greater than 0")
      SEQUENCE += len(data)
      msg = json.dumps({"sequence": SEQUENCE, "data": data, "ack": False, "eof": True})
      if sock.sendto(msg, dest) < len(msg):
        log("[error] unable to fully send packet")
      else:
        PACKETS_MEMORY.append(msg)
        log("[send data] " + str(SEQUENCE) + " (" + str(len(data)) + ")")
        return True
    else:
      return False
  else:
    curSize = 0
    print("dataSize is greater than DATA_SIZE")
    while curSize < dataSize:
#      print("curSize is: ")
#      print(curSize)
      msg = {}
      if dataSize - curSize >= DATA_SIZE:
        Data = data[curSize: curSize+DATA_SIZE + 1]
        curSize += DATA_SIZE
        SEQUENCE += DATA_SIZE
        msg = json.dumps({"sequence": SEQUENCE, "data": Data, "ack": False, "eof": False})
      else:
        Data = data[curSize: (dataSize-curSize)]
        curSize += (dataSize - curSize)
        SEQUENCE += (dataSize - curSize)
        msg = json.dumps({"sequence": SEQUENCE, "data": Data, "ack": False, "eof": True})
#      print("MSG is ")
#      print(msg)
#      print(SEQUENCE)
      if sock.sendto(msg, dest) < len(msg):
        log("[error] unable to fully send packet")
      else:
        log("[send data] " + str(SEQUENCE) + " (" + str(len(data)) + ")")
        PACKETS_MEMORY.append(msg)
        # return True
     # return True 
       

# Send first packet
send_next_packet()

# Now read in data, send packets
while True:
  log("ABOUT TO SLEEP")
  result = sock.recvfrom(MSG_SIZE)
  
  if result:
    (data, addr) = result
    try:
      decoded = json.loads(data)
      if decoded['ack'] == "receiver program ended":
        log("sender receive message from receiver about its exit")
        sys.exit(0)
      if decoded["ack"] == "received the wrong packet, sequence number does not match":
        log("receiver receive wrong packet, try to detect which one and resend")
        # obtain the current sequence number and compare
        SEQ_COUNT = 0
        # determine packet to send
        for count, packet in enumerate(PACKETS_MEMORY):
          if SEQ_COUNT + len(packet['data']) == decoded['seq']:
             if sock.sendto(PACKETS_MEMORY[count + 1], dest) < len(msg):
               log("[error] unable to fully send packet")
             else:
               log("[send data] " + str(SEQUENCE) + " (" + str(len(data)) + ")")
          else:
            SEQ_COUNT += len(packet['data'])
      # If there is an ack, send next packet
      if decoded['ack'] == SEQUENCE:
        log("[recv ack] " + str(SEQUENCE))
        # Try to send next packet; break if no more data
        if (not send_next_packet()):
          break
    except (ValueError, KeyError, TypeError):
      log("[recv corrupt packet]")
  else:
    log("[error] timeout")
    sys.exit(-1)

sock.sendto(json.dumps({"eof": True, "data": "", "sequence": SEQUENCE, "ack": False}), dest)
sys.exit(0)
